name: Pull Request
on:
  pull_request:
    types: [opened, reopened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: cedrickring/golang-action@1.6.0
        with:
          args: |
            go get github.com/golang/mock/mockgen@v1.4.4;
            make mocks;
            make build_ci;
            make test;
  integration_test:
    runs-on: ubuntu-latest
    container: golang:1.15.6-buster
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize Database
        uses: cedrickring/golang-action@1.6.0
        env:
          PG_URL: "postgres://postgres:password@postgres:5432/example?sslmode=disable"
        with:
          args: make migrator && ./bin/migrator init && ./bin/migrator up
      - name: Integration Test
        uses: cedrickring/golang-action@1.6.0
        env:
          PG_URL: "postgres://postgres:password@postgres:5432/example?sslmode=disable"
        with:
          args: make e2e

